---
services:
  boilbot:
    build: .
    container_name: boiler-bot
    restart: unless-stopped
    environment:
      - BOT_TOKEN=${BOT_TOKEN}
      - DISCORD_BOT_GUILD_IDS=${DISCORD_BOT_GUILD_IDS}
    volumes:
      - ./templates:/app/templates
      - ./cache:/app/cache